services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stin_backend
    restart: unless-stopped
    env_file:
      - path: ./backend/.env
        required: false
    volumes:
      - /root/stin/backend:/app
    ports:
      - "8080:8080"
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stin_frontend
    restart: unless-stopped
    env_file:
      - path: ./frontend/.env
        required: false
    volumes:
      - /root/stin/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend